version: '3'

services: 
  
  db:
    container_name: postgres_db 
    image: 'postgres:latest'
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tgl_db
    ports: 
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  
  app:
    container_name: tgl_api
    build: .
    image: tgl_api
    ports: 
      - "3333:3333"
    links: 
      - db
    depends_on: 
      - db
      - migration
      - sheduler
    ports: 
      - "3333:3333"
    command: npm start

  migration:
    container_name: tgl_api_migration
    build: .
    image: tgl_api
    depends_on: 
      - db
    command: node ace migration:run
  

  sheduler:
    container_name: tgl_api_sheduler
    build: .
    image: tgl_api
    depends_on: 
      - migration
    command: node ace scheduler:run

