version: '3'

services: 
  db:
    container_name: postgres_db 
    image: 'postgres:latest'
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tgl_db
    ports: 
      - "5432:5432"